package: #Provides package metadata
    name: leapmotion-blender
    version: 1.0

#source: #Specifies where the source code of the package comes from
#    git_url: git@github.com:ishikKayabas/leapmotion-blender.git

requirements:
    build: #Specifies any packages required to build the package
        - python 3.3*
        - swig

about:
    home: https://github.com/ishikKayabas/leapmotion-blender
    license: BSD

